spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: expo_backend_assignment
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/expo_auth?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
